version: 3

tasks:
  default:
    cmds:
      - echo "Hello, World!"
    deps:
      - clean
      - restore
      - build
      - test
      - deploy
  docker_build:
    cmds:
      - docker buildx build -t elderforge/server .
  clean:
    cmds:
      - dotnet clean
  restore:
    cmds:
      - dotnet restore
  build:
    cmds:
      - dotnet build --no-restore
  test:
    cmds:
      - dotnet test
  publish:
    cmds:
      - dotnet publish ./src/Elderforge.Server/Elderforge.Server.csproj -c Release   -o ./publish
  publish-unity:
    cmds:
      - dotnet publish ./src/Elderforge.Network.Client/Elderforge.Network.Client.csproj -c Release   -o ./publish_unity
    deps:
      - clean
      - restore
  bump-alpha:
    cmds:
      - versionize --pre-release alpha
      - git push --follow-tags origin
